import type { NextPage } from "next";
import { NextSeo } from "next-seo";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <main>
      <NextSeo
        title="Using More of Config"
        description="This example uses more of the available config options."
        canonical="https://www.canonical.ie/"
        openGraph={{
          url: "https://www.url.ie/a",
          title: "Open Graph Title",
          description: "Open Graph Description",
          images: [
            // {
            //   url: 'https://www.example.ie/og-image-01.jpg',
            //   width: 800,
            //   height: 600,
            //   alt: 'Og Image Alt',
            //   type: 'image/jpeg',
            // },
            // {
            //   url: 'https://www.example.ie/og-image-02.jpg',
            //   width: 900,
            //   height: 800,
            //   alt: 'Og Image Alt Second',
            //   type: 'image/jpeg',
            // },
            // { url: 'https://www.example.ie/og-image-03.jpg' },
            { url: "https://www.example.ie/og-image-04.jpg" },
          ],
          site_name: "SiteName",
        }}
        twitter={{
          handle: "@handle",
          site: "@site",
          cardType: "summary_large_image",
        }}
      />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div className={styles.grid}>
            {posts.map((post) => (
              <Card key={post.id} post={post} />
            ))}
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </main>
  );
};

const Card: React.FC<{
  post: {
    id: number;
    title: string;
    description: string;
    link: string;
  };
}> = ({ post }) => {
  return (
    <a href={post.link} className={styles.card}>
      <h2>{post.title}</h2>
      <p>{post.description}</p>
    </a>
  );
};

const posts = [
  {
    id: 1,
    link: "https://nextjs.org/docs",
    title: "Documentation &rarr;",
    description: "Find in-depth information about Next.js features and API.",
  },

  {
    id: 2,
    link: "https://nextjs.org/learn",
    title: "Learn &rarr;",
    description: "Learn about Next.js in an interactive course with quizzes!",
  },
  {
    id: 3,
    link: "https://github.com/vercel/next.js/tree/master/examples",
    title: "Examples &rarr;",
    description: "Discover and deploy boilerplate example Next.js projects.",
  },
  {
    id: 4,
    link: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
    title: "Deploy &rarr;",
    description:
      "Instantly deploy your Next.js site to a public URL with Vercel.",
  },
];

export default Home;
