import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Custom() {
  return (
    <div className={styles.container}>
      <AppHead />

      <MainSection />
    </div>
  );
}

const AppHead = (params) => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

const MainSection = (params) => {
  return (
    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className={styles.description}>
        Get started by editing{" "}
        <code className={styles.code}>pages/index.js</code>
      </p>

      <div className={styles.grid}>
        <Link href="/about">
          <a className={styles.card}>
            <h2>About Page &rarr;</h2>
            <p>Cypress will test if this link is working.</p>
          </a>
        </Link>
      </div>
    </main>
  );
};
